### ISSUE TITLE
Task 1.1_Login & Register Pages

### ISSUE THREAD

**Issue by pkankariya** [rjmfff/CS5551_5-2_Labs#5]
Create login and register pages using OAuth 2.0 service.

**Comment by pkankariya** [comment]
This task shall be started in Lab iteration 1 and will be completed in Lab iteration 2 as the basic structure is built in the first iteration and the functionality is cleaned up in the second.

**Comment by rjmfff** [comment]
commit c92d0a79905c72029b29ca872fcefd266ec87582
