### ISSUE TITLE
Task 3.1.1_Create an About Page

### ISSUE THREAD

**Issue by pkankariya** [rjmfff/CS5551_5-2_Labs#8]
Description of the project idea is displayed to the user on this page.

**Comment by pkankariya** [comment]
This task shall be started in Lab iteration 1 and will be completed in Lab iteration 2 as the basic structure is built in the first iteration and the functionality is cleaned up in the second.

**Comment by pkankariya** [comment]
The structure of the about page is created under this issue.

**Comment by rjmfff** [comment]
Created pages with placeholder texts here: 28b01bf027ba69009d2a3405c0843b9ad169f129
