### ISSUE TITLE
Task 3.2.1_Create a Contact Page

### ISSUE THREAD

**Issue by pkankariya** [rjmfff/CS5551_5-2_Labs#9]
Contact information of the team members shall be displayed to the user on this page. An icon/image shall represent the link to the GitHub assignment repository.

**Comment by pkankariya** [comment]
The structure of the contacts page is updated under this issue.

**Comment by rjmfff** [comment]
Created pages with placeholder texts here: 28b01bf027ba69009d2a3405c0843b9ad169f129
